name: Notify Slack (Reusable)

on:
  workflow_call:
    inputs:
      cypress-status:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Cypress result notification.",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":zap: Cypress Test Results"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "• *Repository:* ${{ github.repository }}\n• *Environment:* DEV\n• *Commit:* `${{ github.sha }}`\n• *Status:* ${{ inputs.cypress-status == 'success' && '✅ Passed' || '❌ Failed' }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": ":eyes: *<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View GitHub Actions Run>*"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
